language: java
jdk: openjdk8

# Services
services:
#  - rabbitmq
  - redis

addons:
  apt:
    packages:
      - rabbitmq-server

before_script:
  # Create directories
  - mkdir webApp/files webApp/qr
  - sudo service redis-server stop
  - sudo redis-server --port 6379 --requirepass mypass >/dev/null 2>&1 &
  - sleep 10 # Sleep 10 seconds



#after_script:
#  # Show error
#  - cat /home/travis/build/piter1902/UrlShortener/build/reports/tests/test/index.html

branches:
  only:
  - master
