# Based on: https://github.com/UNIZAR-30246-WebEngineering/lab1-git-race/blob/master/Dockerfile

#Step 1: Compile
FROM gradle:6.6.1-jdk11 AS build
RUN mkdir -p /code/workers /code/lib
WORKDIR /code
COPY --chown=gradle:gradle settings.gradle /code
COPY --chown=gradle:gradle lib /code/lib
COPY --chown=gradle:gradle workers /code/workers
RUN gradle :workers:bootJar --no-daemon

#Step 2: Run image
FROM openjdk:11-jre-slim
RUN mkdir /app
WORKDIR /app
COPY --from=build /code/workers/build/libs/*.jar /app/workers.jar
ENTRYPOINT ["java"]
CMD ["-jar", "/app/workers.jar"]